name: segment-model
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - cudatoolkit=11.8  # or 12.1 depending on your GPU driver
  - pip:
      - torch>=2.0.0
      - torchvision>=0.15.0
      - ultralytics>=8.0.0
      - nibabel>=5.0.0
      - SimpleITK>=2.2.0
      - pydicom>=2.3.0
      - opencv-python>=4.8.0
      - scikit-image>=0.21.0
      - matplotlib>=3.7.0
      - Pillow>=10.0.0
      - sahi>=0.11.0
      - numpy>=1.24.0,<2.0.0
      - scipy>=1.10.0
      - tqdm>=4.65.0
      - PyYAML>=6.0
      - pandas>=2.0.0
      - black>=23.0.0
      - ruff>=0.0.280
      - jupyter>=1.0.0
      - ipykernel>=6.25.0